import math
from sympy import *
import numpy as np
import matplotlib.pyplot as plt
x=symbols("x")
def tichphan(f,a,b):
    return integrate(f,(x,a,b))
print("Câu a")
print(tichphan(x**3+2*x**2+3,1,2))
print("Câu b")
print(tichphan(1/x**3+1/x**2+x*sqrt(x),1,4))
print("Câu c")
print(tichphan((x**3+x*sqrt(x)+x)/x**2,1,4))
print("Câu d")
print(tichphan(2/x+x**3,1,2))
print("Câu e")
print(tichphan(x**2*(1/x+2*x),1,2))
print("Câu f")
print(tichphan((sqrt(x)-1)*(x+sqrt(x)+1),0,1))
print("Câu g")
print(tichphan(1-2/(sin(x))**2,math.pi/4,math.pi/2))
print("Câu h")
print(tichphan(1/(cos(x)**2+sin(x)**2),math.pi/6,math.pi/4))
print("Câu i")
print(tichphan(exp(x)*(1-exp(-x)/cos(x)**2),0,math.pi/4))
print("Câu j")
print(tichphan(exp(x)*(2+exp(-x)/exp(x)),0,math.pi/4))
print("Câu k")
print(tichphan(x**2*(x-1)**2,0,1))
print("Câu m")
print(tichphan(1/(x*(x+1)),1,2))
print("Câu n")
print(tichphan(abs(1-x),0,2))
print("Câu o")
print(tichphan(abs(2*x-x**2),0,2))
print("Câu p")
print(tichphan(sqrt(x**2-3*x+2),2,4))
print("Câu q")
print(tichphan(sqrt(1+cos(2*x)),0,math.pi))