# -*- coding: utf-8 -*-
"""LAB04&04_01-03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19FEsBy0wtZI0q7enPtFeEdr0nIt7xHb9
"""

from sympy import *
import math
import numpy as np
import matplotlib.pyplot as plt
x,t,z = symbols("x t z")

# EX1
print(" cau a")
f1a =   4- x**2
df1a = diff(f1a,x,1)
print("f(x) dao ham la {}".format(df1a))

print(" cau b")
f1b =   (x-1)**2 + 1
df1b = diff(f1b,x)
print("f(x) dao ham la {}".format(df1b))

print(" cau c")
f1c = 1/t**2
df1c = diff(f1c,t)
print("f(x) dao ham la {}".format(df1c))

print(" cau d")
f1d = (1-z)/(2*z)
df1d = diff(f1d,z)
print("f(x) dao ham la {}".format(df1d))

print(" cau e")
f1e = sqrt(3*z)
df1e = diff(f1e,z)
print("f(x) dao ham la {}".format(df1e))

print(" cau f")
f1f = sqrt(2*z+1)
df1f = diff(f1e,z)
print("f(x) dao ham la {}".format(df1e))

from sympy import *
import math
import numpy as np
import matplotlib.pyplot as plt
# EX2
# tính đường tiếp tuyến 
# y -y0 = f'(x0)(x-x0) => y = f'(x0)(x-x0) + y0
########################## câu a #####################
f2a = x**2 + 1
xa = 2
ya = 5
df1 = diff(f2a,x).subs(x,xa) * (x-xa) + ya
print(" CÂU A :")
print("phương trình tiếp tuyên: {}".format(df1))

val = np.arange(-10,10,0.1)
fval_y = lambdify(x,f2a,"numpy")(val)
fval = lambdify(x,df1,"numpy")(val)

plt.plot(val,fval_y,'r')
plt.plot(val,fval,'b')
plt.plot(xa,ya,'cp')
plt.grid()
plt.show()


########################## câu b #####################
f2b = x - 2*x**2
xb = 1
yb = -1
df2 = diff(f2b,x).subs(x,xb) * (x-xb) + yb
print(" CÂU B :")
print("phương trình tiếp tuyên: {}".format(df2))

val = np.arange(-10,10,0.1)
fval_y = lambdify(x,f2b,"numpy")(val)
fval = lambdify(x,df2,"numpy")(val)

plt.plot(val,fval_y,'r')
plt.plot(val,fval,'b')
plt.plot(xb,yb,'cp')
plt.grid()
plt.show()


########################## câu c #####################
f2c = x/(x-2)
xc = 3
yc = 3
df3 = diff(f2c,x).subs(x,xc) * (x-xc) + yc
print(" CÂU c :")
print("phương trình tiếp tuyên: {}".format(df3))

val = np.arange(-10,10,0.1)
fval_y = lambdify(x,f2c,"numpy")(val)
fval = lambdify(x,df3,"numpy")(val)

plt.plot(val,fval_y,'r')
plt.plot(val,fval,'b')
plt.plot(xc,yc,'cp')
plt.grid()
plt.show()

########################## câu d #####################
f2d = 8/x**2
xd = 2
yd = 2
dfd = diff(f2d,x).subs(x,xd) * (x-xd) + yd
print("phương trình tiếp tuyến là {}".format(dfd))

val = np.arange(-10,10,0.1)
fval_y = lambdify(x,f2d,"numpy")(val)
fval = lambdify(x,dfd,"numpy")(val)

plt.plot(val,fval_y,'r')
plt.plot(val,fval,'g')
plt.plot(xd,yd,'cp')
plt.grid()
plt.show()

########################## câu e #####################
f2e = sqrt(x)
xe = 4
ye = 2
dfe = diff(f2e,x).subs(x,xe) * (x-xe) + ye
print("phương trình tiếp tuyến là {}".format(dfe))

val = np.arange(-10,10,0.1)
fval_y = lambdify(x,f2e,"numpy")(val)
fval = lambdify(x,dfe,"numpy")(val)

plt.plot(val,fval_y,'r')
plt.plot(val,fval,'g')
plt.plot(xe,ye,'cp')
plt.grid()
plt.show()

########################## câu f #####################
f2f = x**3 + 3*x
xf = 1
yf = 4
dff = diff(f2f,x).subs(x,xf) * (x-xf) + yf
print("phương trình tiếp tuyến là {}".format(dff))

val = np.arange(-10,10,0.1)
fval_y = lambdify(x,f2f,"numpy")(val)
fval = lambdify(x,dff,"numpy")(val)

plt.plot(val,fval_y,'r')
#plt.plot(val,fval,'g')
plt.plot(xf,yf,'cp')
plt.grid()
plt.show()


########################## câu g #####################
f2g = 8/sqrt(x-2)
xg = 6
yg = 4
dfg = diff(f2e,x).subs(x,xg) * (x-xg) + yg
print("phương trình tiếp tuyến là {}".format(dfg))

val = np.arange(-10,10,0.1)
fval_y = lambdify(x,f2g,"numpy")(val)
fval = lambdify(x,dfg,"numpy")(val)

plt.plot(val,fval_y,'r')
plt.plot(val,fval,'g')
plt.plot(xg,yg,'cp')
plt.grid()
plt.show()


########################## câu h #####################
f2h = 1 + sqrt(4-x)
xh = 3
yh = 2
dfh = diff(f2h,x).subs(x,xh) * (x-xh) + yh
print("phương trình tiếp tuyến là {}".format(dfh))

val = np.arange(-10,10,0.1)
fval_y = lambdify(x,f2h,"numpy")(val)
fval = lambdify(x,dfh,"numpy")(val)

plt.plot(val,fval_y,'r')
plt.plot(val,fval,'g')
plt.plot(xh,yh,'cp')
plt.grid()
plt.show()

### EX3

from sympy import *
import math
import numpy as np
import matplotlib.pyplot as plt
####### ------- cau a)--------
print("CÂU A :")
x = symbols("x")
f3a = 5*x-3*x**2
ya = f3a.subs(x,1)
dfa = diff(f3a,x)
tinha = dfa.subs(x,1)
print("dao ham tai x = 1 la {}".format(tinha))

tieptuyena = tinha * (x-1) + ya
print("phuong trinh tiep tuyen la {}".format(tieptuyena))

####### ------- cau b)--------
print("CÂU B")
x = symbols("x")
f3b = 1/(x-1)
yb = f3b.subs(x,3)
dfb = diff(f3b,x)
tinhb = dfb.subs(x,3)
print("dao ham tai x = 3 la {}".format(tinhb))

tieptuyenb = tinhb * (x-3) + yb
print("phuong trinh tiep tuyen la {}".format(tieptuyenb))

####### ------- cau c)--------
print("CÂU C")
x = symbols("x")
f3c = x**3 -2*x + 7
yc = f3c.subs(x,-2)
dfc = diff(f3c,x)
tinhc = dfc.subs(x,-2)
print("dao ham tai x = -2 la {}".format(tinhc))

tieptuyenc = tinhc * (x--2) + yc
print("phuong trinh tiep tuyen la {}".format(tieptuyenc))


####------ câu d)----------
print("CÂU D")

f3d = (x-1)/(x+1)
yd = f3d.subs(x,0)
dfd = diff(f3d,x)
tinhd = dfd.subs(x,0)
print("dao ham x = 0 la {}".format(tinhd))

tieptuyend = tinhd * (x-0) + yd
print("phương trình tiếp tuyến la {}".format(tieptuyend))

