# -*- coding: utf-8 -*-
"""LAB03_1-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UExOYN7Qcxz4cyGsiblnXFk01mMXpDV7
"""

## EX1 AND EX2 TÍNH LIM VÀ VẼ ĐỒ THỊ
###### câu A:
from sympy import *
import math
import numpy as np
import matplotlib.pyplot as plt

x,y = symbols("x y")

f1a = abs(x**2 - x -7)
kqa = limit(f1a,x,3)
print("câu a : tại x = 3, f(x) : {}".format(kqa))

val_xa = np.arange(1,10,0.1)
val_ya = lambdify(x,f1a,"numpy")(val_xa)

plt.plot(val_xa,val_ya,"r")
plt.plot(3,kqa,"o")
plt.show()

### CÂU B: 
f1b = abs(x-1)/(x**2-1)
kqb = limit(f1b,x,1)
print("câu b : tại x = 1, f(x) : {}".format(kqb))

val_xa = np.arange(1,10,0.1)
val_yb = lambdify(x,f1b,"numpy")(val_xa)

plt.plot(val_xa,val_yb,"r")
plt.plot(1,kqb,"o")
plt.show()


### CÂU C:
f1c = exp(1/x)
kqc = limit(f1c,x,1)
print("câu c : tại x = 1, f(x) : {}".format(kqc))

val_yc = lambdify(x,f1c,"numpy")(val_xa)

plt.plot(val_xa,val_yc,"r")
plt.plot(1,kqc,"o")
plt.show()

### CÂU D:
f1d = (x**4-16)/(x-2)
kqd = limit(f1d,x,2)
print("câu d : tại x = 2, f(x) : {}".format(kqd))

val_yd = lambdify(x,f1d,"numpy")(val_xa)

plt.plot(val_xa,val_yd,"r")
plt.plot(2,kqd,"o")
plt.show()

#### CÂU E:
f1e = (x**3-x**2-5*x-3)/(x+1)**2
kqe = limit(f1e,x,-1)
print("câu e : tại x = -1, f(x) : {}".format(kqe))

val_ye = lambdify(x,f1e,"numpy")(val_xa)

plt.plot(val_xa,val_ye,"r")
plt.plot(-1,kqe,"o")
plt.show()

####  CÂU F:
f1f = (x**2-9)/(sqrt(x**2+7)-4)
kqf = limit(f1f,x,3)
print("câu f : tại x = 3, f(x) : {}".format(kqf))

val_yf = lambdify(x,f1f,"numpy")(val_xa)

plt.plot(val_xa,val_yf,"r")
plt.plot(3,kqf,"o")
plt.show()
 
 ####  CÂU G:
f1g = abs(x)/sin(x)
kqg = limit(f1g,x,1)
print("câu g : tại x = 1, f(x) : {}".format(kqg))

val_yg = lambdify(x,f1g,"numpy")(val_xa)

plt.plot(val_xa,val_yg,"r")
plt.plot(1,kqg,"o")
plt.show()

#####  CÂU H:
f1h = (1-cos(x))/(x*sin(x))
kqh = limit(f1h,x,0)
print("câu h : tại x = 0, f(x) : {}".format(kqh))

val_yh = lambdify(x,f1h,"numpy")(val_xa)

plt.plot(val_xa,val_yh,"r")
plt.plot(3,kqa,"o")
plt.show()

####  CÂU I:
f1i = 2*x**2/(3-3*cos(x))
kqi = limit(f1i,x,0)
print("câu i : tại x = 0, f(x) : {}".format(kqi))

val_yi = lambdify(x,f1i,"numpy")(val_xa)

plt.plot(val_xa,val_yi,"r")
plt.plot(0,kqi,"o")
plt.show()

####  CÂU J:
f1j = ((3+x)/(-1+x))**x
kqj = limit(f1j,x,oo)
print("câu j : tại x = vô cùng, f(x) : {}".format(kqj))

val_yj = lambdify(x,f1j,"numpy")(val_xa)

plt.plot(val_xa,val_yj,"r")
plt.plot(oo,kqj,"ro")
plt.show()

####  CÂU K: 
f1k = (1-2/(3+x))**x
kqk = limit(f1k,x,oo)
print("câu k : tại x = vô cùng, f(x) : {}".format(kqk))

val_yk = lambdify(x,f1k,"numpy")(val_xa)

plt.plot(val_xa,val_yk,"r")
plt.plot(oo,kqk,"ro")
plt.show()

#### CÂU L 
f1l = (1/x)**(1/x)
kql = limit(f1l,x,oo)
print("câu l : tại x = vô cùng, f(x) : {}".format(kql))

val_yl = lambdify(x,f1l,"numpy")(val_xa)

plt.plot(val_xa,val_yl,"r")
plt.plot(oo,kql,"ro")
plt.show()

###  CÂU M:
f1m = (-x**1/3 + (1+x)**1/3)/( -sqrt(x)+ sqrt(1+x))
kqm = limit(f1m,x,oo)
print("câu m : tại x = vô cùng, f(x) : {}".format(kqm))

val_ym = lambdify(x,f1m,"numpy")(val_xa)

plt.plot(val_xa,val_ym,"r")
plt.plot(oo,kqm,"ro")
plt.show()

###  CÂU N:
f1n = factorial(x)/x**x
kqn = limit(f1n,x,oo)
print("câu n : tại x = vô cùng, f(x) : {}".format(kqn))



def f(x):
    return sympy.factorial(x)/x**x
f2 = np.vectorize(f)
x = np.arange(1, 15.1, 0.1)

plt.plot(x, f2(x))
plt.plot(oo,kqn,"o")
plt.show()

#### EXP 3
####### caau A:
x = symbols("x")
fx1 = 1/ (1+2**(1/x))
fx3_11 = limit(fx1,x,0,dir = "-")
fx3_12 = limit(fx1,x,0,dir = "+")
fx3_13 = limit(fx1,x,0)
print("lim f(x)->0- = {}".format(fx3_11))
print("lim f(x)->0+ = {}".format(fx3_12))
print("lim f(x)->0 = {}".format(fx3_13))

val_x = np.arange(1,10,0.1)
val_y1 = lambdify(x,fx1,"numpy")(val_x)

plt.plot(val_xa,val_y1,"r")
plt.grid()
plt.show()

####### caau B:

fx2 = (x**2+x)/(sqrt(x**3+x**2))
fx3_21 = limit(fx2,x,0,dir = "-")
fx3_22 = limit(fx2,x,0,dir = "+")
fx3_23 = limit(fx2,x,0)

print("lim f(x)->0- = {}".format(fx3_21))
print("lim f(x)->0+ = {}".format(fx3_22))
print("lim f(x)->0 = {}".format(fx3_23))

print("HÀM FX KHÔNG TỒN TẠI VÌ LIM x-> 0- khác LIM x-> 0+")

### EXP 4
from sympy import *
import math
import numpy as np
import matplotlib.pyplot as plt

x = symbols("x")

fx1 =sin(1/x)
fx2 = 0

fxcong = limit(fx2,x,0,"+")
print("lim f(x) x->0+ = {}".format(fxcong))

fxtru = limit(fx1,x,0,"-")
print("lim f(x) x->0+- = {}".format(fxtru))

val_xxx = np.arange(-5,5,0.1)
val_yyy = lambdify(x,fx1,"numpy")(val_xxx)

plt.plot(val_xxx,val_yyy,color = "r")
plt.grid()
plt.show()