# -*- coding: utf-8 -*-
"""LAB03_05-10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HMBc741xjOdL_YpuBQorDARU8HSXFRb5
"""

from sympy import *
import math
import numpy as np
import matplotlib.pyplot as plt
import inspect

# EX5a:
x = symbols("x")
fx5a = x**2 -7

# f(x) tai x =1
fa = fx5a.subs(x,1)
print("cau a")
print("f(x) = {}".format(fa))
# lim trai f(x)
limx5atrai = limit(fx5a,x,1,'+')
# lim phai f(x)
limx5aphai = limit(fx5a,x,1,'-')

print("lim trai cua fx : {}".format(limx5atrai))
print("lim phai cua fx : {}".format(limx5aphai))

if fa == limx5atrai == limx5aphai:
  print("f(x) lien tuc tai x = 1")
else:
  print("f(x) khong lien tuc tai x = 1")


# EX5b:

fx5b = sqrt(2*x-3)

# f(x) tai x =2
fb = fx5b.subs(x,2)
print("cau b")
print("f(x) = {}".format(fb))
# lim trai f(x)
limx5btrai = limit(fx5b,x,2,'+')
# lim phai f(x)
limx5bphai = limit(fx5b,x,2,'-')

print("lim trai cua fx : {}".format(limx5btrai))
print("lim phai cua fx : {}".format(limx5bphai))

if fb == limx5btrai == limx5bphai:
  print("f(x) lien tuc tai x = 2")
else:
  print("f(x) khong lien tuc tai x = 2")

# EX6

# cau a
print("cau a")
fx6a = (x**2-x-6)/(x-3)
print("f(x) = ",5)

#limtrai
lim6at = limit(fx6a,x,0,'-')
print("lim trai la = {}".format(lim6at))

#limphai
lim6ap = limit(fx6a,x,0,'+')
print("lim phai la = {}".format(lim6ap))

if 5 == lim6ap == lim6at:
  print("f(x) lien tuc tai x = 0")
else:
  print("f(x) khong lien tuc tai x = 0")



# cau c
print("cau c")
fx6c = (x**2-x-2)/(x-2)
print("f(x) = ",1)

#limtrai
lim6ct = limit(fx6c,x,2,'-')
print("lim trai la = {}".format(lim6ct))

#limphai
lim6cp = limit(fx6a,x,2,'+')
print("lim phai la = {}".format(lim6cp))

if 1 == lim6cp == lim6ct:
  print("f(x) lien tuc tai x = 2")
else:
  print("f(x) khong lien tuc tai x = 2")


# cau d
print("cau d")
fx6d = 1/(x**2)
print("f(x) = ",1)

#limtrai
lim6dt = limit(fx6d,x,0,'-')
print("lim trai la = {}".format(lim6ct))

#limphai
lim6dp = limit(fx6a,x,0,'+')
print("lim phai la = {}".format(lim6dp))

if 1 == lim6dp == lim6dt:
  print("f(x) lien tuc tai x = 0")
else:
  print("f(x) khong lien tuc tai x = 0")


#cau b
print("cau b")
print("f(2) = ",3)
print("f(-2) = ",4)

fx6b = (x**3-8)/(x**2-4)

#lim trai cua x = 2
limtrai1 = limit(fx6b,x,2,'-')
print("lim trai la = {}".format(limtrai1))

#lim phai cua x = 2
limphai1 = limit(fx6b,x,2,'+')
print("lim phai la = {}".format(limphai1))

#lim trai cua x = -2
limtrai2 = limit(fx6b,x,-2,'-')
print("lim trai la = {}".format(limtrai2))

#lim phai cua x = -2
limphai2 = limit(fx6b,x,-2,'+')
print("lim phai la = {}".format(limphai2))

if 3 == limtrai1 == limphai1:
  print("fx lien tuc lai x = 2")
else:
  print("fx khong lien tuc tai x = 2")


if 4 ==limtrai2 == limphai2:
    print("fx lien tuc tai x = 2, x=-2")
else:
    print("fx khong lien tuc  x=-2")

# EX7
from sympy import *
import math
import numpy as np
import matplotlib.pyplot as plt
x = symbols("x")
print("cau a")
fx7a = (x**2-x-2)/(x-2)

f7a = fx7a.subs(x,2)
print("fx = {}".format(f7a))

lim7a = limit(fx7a,x,2)
print("lim = {}".format(lim7a))

if f7a == lim7a:
  print("ham lien tuc tai x = 2")
else:
  print("ham khong lien tuc x =2")


# cau b
print("cau b")
fx7b = (x**2-2*x-3)/(2*x-6)

f7b = fx7b.subs(x,3)
print("fx = {}".format(f7b))

lim7b = limit(fx7b,x,3)
print("lim = {}".format(lim7b))

if f7b == lim7b:
  print("ham lien tuc tai x = 3")
else:
  print("ham khong lien tuc x =3")

# EX8
fx8 = 1-sqrt(1-x**2)

limf81 = limit(fx8,x,-1)
print("lim f(x) x = -1 la {}".format(limf81))

limf82 = limit(fx8,x,1)
print("lim f(x) x = 1 la {}".format(limf82))

if limf81 == limf82:
  print("fx lien tuc tren [-1;1]")
else:
  print("fx khong lien tuc tren [-1;1]")

# EX9


def HeSoGoc(xP, yP, x):
  y = sin(10*math.pi/x)
  return (y-yP)/(x-xP)

xP = 1
yP = 0
print("hệ số góc x = 2 là {}".format(HeSoGoc(xP,yP,2)))
print("hệ số góc x = 1.5 là {}".format(HeSoGoc(xP,yP,1.5)))
print("hệ số góc x = 1.4 là {}".format(HeSoGoc(xP,yP,1.4)))
print("hệ số góc x = 1.3 là {}".format(HeSoGoc(xP,yP,1.3)))
print("hệ số góc x = 0.5 là {}".format(HeSoGoc(xP,yP,0.5)))
print("hệ số góc x = 0.8 là {}".format(HeSoGoc(xP,yP,0)))

## EX10
print("cau a")

f10a = sin(x)/x

lim10a = limit(f10a,x,0)
print("lim cau a = {}".format(lim10a))

print("de f(x) lien tuc lim f(x) = L")
L = lim10a
print("L = ",L)

print("cau b")

f10b = (x**2+x-6)/(x**2-4)

lim10b = limit(f10b,x,2)
print("lim cau b = {}".format(lim10b))

print("de f(x) lien tuc lim f(x) = L")
L = lim10b
print("L = ",L)